export const Host = 'http://localhost:3001/'; //'https://orsnodejs.herokuapp.com/'
export const FetchCategoryApi = Host + 'FetchCategory';
export const UpdateCategoryApi = Host + 'UpdateCategory';
export const CreateCategoryApi = Host + 'CreateCategory';
export const DeleteCategoryApi = Host + 'DeleteCategory';
export const FetchProductApi = Host + 'FetchProduct';
export const UpdateProductApi = Host + 'UpdateProduct';
export const DeleteProductApi = Host + 'DeleteProduct';
export const CreateProductApi = Host + 'CreateProduct';
export const FetchCustomerApi = Host + 'GetCustomer';
export const FetchCustomerExtrasApi = Host + 'GetCustomerExtras';
export const SynchroniseDatabaseApi = Host + 'SynchroniseDatabase';
//# sourceMappingURL=ApiConfig.js.map